apiVersion: v1
kind: Secret
metadata:
  name: hasura
stringData:
  accessKey: accessKey
  # only change postgres username, password and dbname as set
  # in postgres secret
  dburl: postgres://username:password@postgres:5432/dbname
