---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-triggers
spec:
  selector:
    matchLabels:
      app: event-triggers
  template:
    metadata:
      labels:
        app: event-triggers
    spec:
      containers:
      - name: event-triggers
        image: hasura/k8s-stack-event-triggers:6c3a63c
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: event-triggers
spec:
  selector:
    app: event-triggers
  ports:
  - port: 80
    targetPort: 3000
